const data = [
    {
      "login": "996icu",
      "id": 48942249,
      "node_id": "MDQ6VXNlcjQ4OTQyMjQ5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/48942249?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/996icu",
      "html_url": "https://github.com/996icu",
      "followers_url": "https://api.github.com/users/996icu/followers",
      "following_url": "https://api.github.com/users/996icu/following{/other_user}",
      "gists_url": "https://api.github.com/users/996icu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/996icu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/996icu/subscriptions",
      "organizations_url": "https://api.github.com/users/996icu/orgs",
      "repos_url": "https://api.github.com/users/996icu/repos",
      "events_url": "https://api.github.com/users/996icu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/996icu/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 1354
    },
    {
      "login": "ChangedenCZD",
      "id": 9605663,
      "node_id": "MDQ6VXNlcjk2MDU2NjM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/9605663?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ChangedenCZD",
      "html_url": "https://github.com/ChangedenCZD",
      "followers_url": "https://api.github.com/users/ChangedenCZD/followers",
      "following_url": "https://api.github.com/users/ChangedenCZD/following{/other_user}",
      "gists_url": "https://api.github.com/users/ChangedenCZD/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ChangedenCZD/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ChangedenCZD/subscriptions",
      "organizations_url": "https://api.github.com/users/ChangedenCZD/orgs",
      "repos_url": "https://api.github.com/users/ChangedenCZD/repos",
      "events_url": "https://api.github.com/users/ChangedenCZD/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ChangedenCZD/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 49
    },
    {
      "login": "bofeiw",
      "id": 34177142,
      "node_id": "MDQ6VXNlcjM0MTc3MTQy",
      "avatar_url": "https://avatars2.githubusercontent.com/u/34177142?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bofeiw",
      "html_url": "https://github.com/bofeiw",
      "followers_url": "https://api.github.com/users/bofeiw/followers",
      "following_url": "https://api.github.com/users/bofeiw/following{/other_user}",
      "gists_url": "https://api.github.com/users/bofeiw/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bofeiw/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bofeiw/subscriptions",
      "organizations_url": "https://api.github.com/users/bofeiw/orgs",
      "repos_url": "https://api.github.com/users/bofeiw/repos",
      "events_url": "https://api.github.com/users/bofeiw/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bofeiw/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 26
    },
    {
      "login": "xianfengting",
      "id": 23656058,
      "node_id": "MDQ6VXNlcjIzNjU2MDU4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/23656058?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/xianfengting",
      "html_url": "https://github.com/xianfengting",
      "followers_url": "https://api.github.com/users/xianfengting/followers",
      "following_url": "https://api.github.com/users/xianfengting/following{/other_user}",
      "gists_url": "https://api.github.com/users/xianfengting/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/xianfengting/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/xianfengting/subscriptions",
      "organizations_url": "https://api.github.com/users/xianfengting/orgs",
      "repos_url": "https://api.github.com/users/xianfengting/repos",
      "events_url": "https://api.github.com/users/xianfengting/events{/privacy}",
      "received_events_url": "https://api.github.com/users/xianfengting/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 23
    },
    {
      "login": "CPdogson",
      "id": 49220384,
      "node_id": "MDQ6VXNlcjQ5MjIwMzg0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/49220384?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CPdogson",
      "html_url": "https://github.com/CPdogson",
      "followers_url": "https://api.github.com/users/CPdogson/followers",
      "following_url": "https://api.github.com/users/CPdogson/following{/other_user}",
      "gists_url": "https://api.github.com/users/CPdogson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CPdogson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CPdogson/subscriptions",
      "organizations_url": "https://api.github.com/users/CPdogson/orgs",
      "repos_url": "https://api.github.com/users/CPdogson/repos",
      "events_url": "https://api.github.com/users/CPdogson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CPdogson/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 20
    }
  ];

module.exports = {data}